### ISSUE TITLE
Mods Can't Be Configured

### ISSUE THREAD

**Issue by KarlCantCode** [puppy-girl/TackleBox#3]
Mods on the list that should have config menus have no button to access those menus.
![20241114131647_1](https://github.com/user-attachments/assets/30d0ed17-663f-46c4-93af-4fcf5480b805)
In this screenshot, the mods Lure and AlternateVoices should have config buttons, but do not.

**Comment by bizzlemip2** [comment]
Ive found the reason for the bug, if the mods id contains a dot tacklebox cant find it.

**Comment by bizzlemip2** [comment]
Ive created a pull request that fixes this bug.

**Comment by puppy-girl** [comment]
Fixed! pushing an update now, thanks for the shout

**Comment by ketn-0** [comment]
Hii uuh mods still can't be configured!! x3
The config button is still missing and the mod version is one less than it should be

**Comment by puppy-girl** [comment]
> Hii uuh mods still can't be configured!! x3 The config button is still missing and the mod version is one less than it should be

im aware of the version mismatch, that was a mistake on my end; configs should be fine now, however. could you double check that you have the latest version from thunderstore?

**Comment by ketn-0** [comment]
OH!! The one from thunderstore works c: !!
Thank you,
